name: python_exercise
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib

  # for the exercises on pypsa
  - pypsa>=1
  - glpk
  - gurobi  # not necessary but can ease the usability for some users

  # for jupyter
  - jupyter
  - ipython
  - ipykernel
